### ISSUE TITLE
Restore contents of clip_len.json

### ISSUE THREAD

**Issue by fitwist** [shangar21/compubox#3]
Could you please upgrade .gitignore file and allow committing clip_len.json? I've cloned the repository, installed the dependencies and now rnn.py fails to read info_path:

(compubox_dev) username@machine compubox % python3 main.py -p ./samples/dataset

```
WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 776.8ms
video 1/1 (2/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 685.6ms
video 1/1 (3/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 682.2ms
video 1/1 (4/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 637.3ms
video 1/1 (5/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 604.9ms
video 1/1 (6/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 591.3ms
video 1/1 (7/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 588.1ms
video 1/1 (8/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 605.0ms
video 1/1 (9/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 616.0ms
video 1/1 (10/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 609.4ms
video 1/1 (11/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 638.4ms
video 1/1 (12/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 630.8ms
video 1/1 (13/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 626.4ms
video 1/1 (14/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 616.1ms
video 1/1 (15/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 639.6ms
video 1/1 (16/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 721.4ms
video 1/1 (17/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 751.4ms
video 1/1 (18/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 672.4ms
video 1/1 (19/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 609.6ms
video 1/1 (20/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 619.5ms
video 1/1 (21/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 644.8ms
video 1/1 (22/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 740.1ms
video 1/1 (23/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 618.4ms
video 1/1 (24/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 604.9ms
video 1/1 (25/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 592.6ms
video 1/1 (26/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 590.0ms
video 1/1 (27/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 612.4ms
video 1/1 (28/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 596.3ms
video 1/1 (29/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 598.0ms
video 1/1 (30/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 604.6ms
video 1/1 (31/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 594.6ms
video 1/1 (32/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 597.3ms
video 1/1 (33/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 594.1ms
video 1/1 (34/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 596.2ms
video 1/1 (35/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 594.7ms
video 1/1 (36/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 599.0ms
video 1/1 (37/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 599.7ms
video 1/1 (38/38) /Users/elenakapatsa/Repositories/compubox/samples/dataset/cross_hook.mp4: 640x384 2 persons, 600.3ms
Speed: 2.1ms preprocess, 628.9ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 384)
Traceback (most recent call last):
  File "/Users/elenakapatsa/Repositories/compubox/main.py", line 55, in <module>
    punches = rnn.predict(X)
              ^^^^^^^^^^^^^^
  File "/Users/elenakapatsa/Repositories/compubox/compubox/rnn.py", line 40, in predict
    clip_info = json.load(open(info_path, 'r'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by shangar21** [comment]
Thanks for letting me know about the issue, I have added the clip_len.json that was used for this implementation.

**Comment by fitwist** [comment]
> Thanks for letting me know about the issue, I have added the clip_len.json that was used for this implementation.

Thanks a lot, the issue is resolved)
